### ISSUE TITLE
May I ask you a question

### ISSUE THREAD

**Issue by yu600** [hmrc/individuals-income-received-api#174]
Excuse me, I'm sorry to bother you, but may I ask you a question?
I am a Java developer, I encountered problems in API calls to HMRC in the development of the, I don't know how to call the Agent in the sandbox Authorisation of API interface, API address: https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/agent-authorisation-api/1.0.
I can now create get access tokens in the sandbox, I can create test users, but I can't do how to invoke the Agent Authorisation API.
For example: create a new Authorization, which account to obtain Authorization?Where do arN parameters come from?I'm using it in a sandbox, can you explain in detail how to call the API and where to get the parameters?

**Comment by hmrc-api-team** [comment]
Hi @yu600 

We only provide support to technical questions regarding our team's APIs, in this `individuals-income-received-api`. We don't actually support the Agents APIs and would advise you to contact the Software Developers Support Team at SDSTeam@hmrc.gov.uk for assistance.

I have however just tried this out myself and I was able to get an Agent user working. The guide that our develop team follows is here https://github.com/hmrc/self-assessment-api/wiki/Creating-Test-Agents-in-the-Sandbox. 

We can't offer any further assistance if you run into trouble with any of the Agent or Auth services, so please contact SDST if you have any problems.

Regards

**Comment by yu600** [comment]
Thank you very much for taking the time to answer my question. I followed the instructions you gave and successfully called the Agent API.
I couldn't find where to get the arguments in the API and couldn't call them successfully, so I was stuck here for a long time and I was about to crash.But now I can call it successfully.So thank you very much for your help!

**Comment by yu600** [comment]
Excuse me, I'm sorry to bother you again, but may I ask you one more question?
I now have two accounts, an agent and a user, both created by the API.
When I call VAT (MTD) API (https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0#_submit-vat-return-for-period_post_accordion)
It is ok to use the user's account, but not the agent's account
say "code": "CLIENT_OR_AGENT_NOT_AUTHORISED", "message": "The client and/or agent is not authorised.".
 VRN is the user's VRN.So how can I use the agent's account to give the user agent?
If the Agent Authorisation API is needed, I should have done it.
![Uploading XC($@6{VLSBL23[0BH7RH%U.png…]()
So what else should I do?Or the agent's account is not the agent?

**Comment by yu600** [comment]
![XC($@6{VLSBL23 0BH7RH%U](https://user-images.githubusercontent.com/53322378/94359211-4c6bc800-00d8-11eb-9958-1442a9cd0496.png)
